version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: adaplio-mailhog
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    environment:
      - MH_STORAGE=memory