services:
  - type: web
    name: adaplio-api
    runtime: docker
    plan: free
    buildCommand: docker build .
    startCommand: dotnet Adaplio.Api.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ISSUER
        value: adaplio-api
      - key: JWT_AUDIENCE
        value: adaplio-frontend
      - key: CORS__ORIGINS
        value: https://adaplio.com,https://www.adaplio.com,https://tyreamer.github.io,http://localhost:5173,https://localhost:5173,https://adaplio.vercel.app
    healthCheckPath: /