name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write    # <— important

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET (8.x to match your project)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install wasm-tools workload
        run: dotnet workload install wasm-tools

      - name: Publish Blazor
        run: |
          dotnet publish src/Frontend/Adaplio.Frontend -c Release -o publish
          ls -R publish
          # For custom domain, use root path instead of /adaplio/
          sed -i 's|<base href="/" />|<base href="/" />|' publish/wwwroot/index.html
          # Copy CNAME file for custom domain
          cp CNAME publish/wwwroot/

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: publish/wwwroot
